2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Configure stats pid to 4084
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Loading settings from /Users/ruthikkale/.config/wandb/settings
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Loading settings from /Users/ruthikkale/Documents/GitHub/StockX/single_stock/wandb/settings
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-05 14:40:26,227 INFO    MainThread:4084 [wandb_init.py:_log_setup():521] Logging user logs to /Users/ruthikkale/Documents/GitHub/StockX/single_stock/wandb/run-20240505_144026-3qlahksl/logs/debug.log
2024-05-05 14:40:26,228 INFO    MainThread:4084 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/ruthikkale/Documents/GitHub/StockX/single_stock/wandb/run-20240505_144026-3qlahksl/logs/debug-internal.log
2024-05-05 14:40:26,228 INFO    MainThread:4084 [wandb_init.py:init():561] calling init triggers
2024-05-05 14:40:26,228 INFO    MainThread:4084 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-05 14:40:26,228 INFO    MainThread:4084 [wandb_init.py:init():586] re-initializing run, found existing run on stack: 22wrefgj
2024-05-05 14:40:26,229 INFO    MainThread:4084 [wandb_run.py:_finish():2064] finishing run rk42218/LSTM/22wrefgj
2024-05-05 14:40:26,230 INFO    MainThread:4084 [jupyter.py:save_history():445] not saving jupyter history
2024-05-05 14:40:26,230 INFO    MainThread:4084 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-05 14:40:26,230 INFO    MainThread:4084 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-05-05 14:40:26,230 INFO    MainThread:4084 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-05 14:40:26,230 INFO    MainThread:4084 [wandb_run.py:_restore():2287] restore
2024-05-05 14:40:26,230 INFO    MainThread:4084 [wandb_run.py:_restore():2293] restore done
2024-05-05 14:41:52,531 INFO    MainThread:4084 [wandb_init.py:init():611] starting backend
2024-05-05 14:41:52,532 INFO    MainThread:4084 [wandb_init.py:init():615] setting up manager
2024-05-05 14:41:52,541 INFO    MainThread:4084 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-05 14:41:52,541 INFO    MainThread:4084 [wandb_init.py:init():623] backend started and connected
2024-05-05 14:41:52,559 INFO    MainThread:4084 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-05-05 14:41:52,559 INFO    MainThread:4084 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-05 14:41:52,559 INFO    MainThread:4084 [wandb_init.py:init():715] updated telemetry
2024-05-05 14:41:52,660 INFO    MainThread:4084 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-05 14:41:55,466 WARNING MainThread:4084 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/Users/ruthikkale/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ruthikkale/anaconda3/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
